name: workflow events
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: print trigger name
          run:  echo "event name for this job :- ${{toJson(github.event_name)}}"
