name: workflow events
on:
  schedule:
    - cron: '1 18 5 12 4'
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: print event name
          run:  echo "event name for this job :- ${{toJson(github.event_name)}}"
