name: day3-hands-on
on:
  push:
    branches:
      - master
      - feature1
      - feature2
  issues:
    types:
      - opened
      - closed
  pull_request:
    types:
      - opened
jobs:
  test_workflow_triggers:
    runs-on: ubuntu-latest
    steps:
      - name: print trigger name
        run: |
          echo "workflow triggered by ${{github.event_name}}"