name: day4-hands-on-python
on:
  workflow_dispatch:
jobs:
  python-app:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4

      - name: set-up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build App
        run: |
          mkdir -p build
          cp -r myapp-py build/
          cp requirements.txt build/
          tar -cvzf myapp-py.tar.gz -C build .
          
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: myapp-py
          path: myapp-py.tar.gz