name: day4-hands-on-python
on:
  workflow_dispatch:
jobs:
  python-app:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4

      - name: set-up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip freeze > requirements.txt
          pip install -r requirements.txt

      - name: Build App
        run: |
          pip install bmi
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/