name: test-oidc
on:
  workflow_dispatch:
jobs:
  check-oidc:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: aws intergation using OIDC
        uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::736218978384:role/GA_OIDC
            aws-region: ap-south-1
